# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Fu_Quantong/project_15/project_15.srcs/sources_1/ip/ASCII_ROM/ASCII_ROM.xci
# IP: The module: 'ASCII_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fu_Quantong/project_15/project_15.gen/sources_1/ip/ASCII_ROM/ASCII_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASCII_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Fu_Quantong/project_15/project_15.srcs/sources_1/ip/ASCII_ROM/ASCII_ROM.xci
# IP: The module: 'ASCII_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fu_Quantong/project_15/project_15.gen/sources_1/ip/ASCII_ROM/ASCII_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASCII_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
