# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Fu_Quantong/project_14/project_14.srcs/sources_1/ip/Fudan320x320/Fudan320x320.xci
# IP: The module: 'Fudan320x320' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fu_Quantong/project_14/project_14.gen/sources_1/ip/Fudan320x320/Fudan320x320_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fudan320x320'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Fu_Quantong/project_14/project_14.srcs/sources_1/ip/Fudan320x320/Fudan320x320.xci
# IP: The module: 'Fudan320x320' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fu_Quantong/project_14/project_14.gen/sources_1/ip/Fudan320x320/Fudan320x320_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fudan320x320'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
